### ISSUE TITLE
Project Outline: Technologies

### ISSUE THREAD

**Issue by lindskelsey** [nsumma147/liftoff-assignments#2]
A few notes on your technologies--

AngularJS: I would highly encourage you to use Angular over AngularJS, unless you are already familiar with AngularJS. Using the newer version will have an easier learning curve.

Backend language: I see you've mentioned the MEAN stack but have no backend technologies listed. If you're using MEAN, that would be Node. You can write an API using Node, and have Angular consume that API.

I would like to hear more about your experience with these technologies. Are Node, Angular, and MongoDB all completely new to you?

**Comment by nsumma147** [comment]
I will definitely take your advice to use Angular over AngularJS. Also I did mean to put Node in my project outline. In terms of familiarity, I am most familiar with Angular, then Node, then MongoDB. I have used them a little in the past, but when I met with Ryan Walker last month he suggested getting more acquainted with MongoDB and the MEAN stack for this class and I have been trying to familiarize myself with it since then, so I would say not completely new, but I would consider myself a beginner with some of these technologies.

 I did think this class was more to help with some of the complex coding when building a project and not as focused on the concepts and planning/execution of making a project, so I am worried about completing everything on the actual coding side of this class, but I am working hard at trying to get better with these technologies.

**Comment by lindskelsey** [comment]
@nsumma147 I think if you already have some exposure & you've already consulted with Ryan, you're in a good place. Angular has the steepest learning curve of the technologies you've listed, so if you have the most experience with that, I think Node/Mongo will come a little easier. In my opinion, Node feels very much like straight JavaScript with some extras thrown in.

As far as the concern about getting help with coding, I'm more familiar with your tech stack than what most of the other students are working on, so please don't hesitate to ask for help. Also like I mentioned in class, I have a bunch of resources I can share with you.
